### ISSUE TITLE
Добавить достижения (ачивки)

### ISSUE THREAD

**Issue by antonkanin** [pauldyatlov/beardythedigger#12]
- [x] Пивка для рывка | Один раз можно | Один раз не грех - Успешно пройти уровень в состоянии опьянения (под зельем) #63 **(Изменено на пройти под любым зельем)**

- [x] В ломбард ювелирных изделий - Собрать 16 алмазов

- [x] Глаз, да алмаз | Глаз, как алмаз - Собрать 32 алмаза

- [x] Ювелирная тонкость | Мастер ювелирных работ | Голубой олигарх | Кристальная лихорадка - Собрать 64 алмаза

- [x] Не всё то Алмаз, что хорошо блестит (секретное достижение) - Пройти 5 уровней подряд, собрав 1 алмаз

- [x] С лёгким паром - Прыгнуть с катапульты #59

- [x] Море по колено (секретное достижение) - Использовать катапульту в состоянии опьянения #59 **(Изменено на использовать катапульту в состоянии отравления)**

- [x] Гори-гори ясно - Умрите от лавы 4 раза

- [x] Достижение | Баланс | Проведите 30 секунд подряд, балансируя на ледяном кубе (секретное достижение) #54 

- [x] Кишки наружу | Позвольте сдвигающимся кубам расплющить вас #66

- [x] Зимний покров - Успешно завершить зимние уровни, собрав 50 кристаллов #74

- [x] Летний урожай - Успешно завершить летние уровни, собрав 50 кристаллов #74

- [x] Куда делся мой ключ? | И так сойдёт - пройти уровень не воспользовавшись ключом #68

**Comment by kotovdv** [comment]
Меняем ачивки 
* Море по колено (секретное достижение) - Использовать катапульту в состоянии опьянения 
- **Использовать в состоянии isPoisoned**

* Пивка для рывка | Один раз можно | Один раз не грех - Успешно пройти уровень в состоянии опьянения (под зельем) - **(Пройти под любым зельем)**
